### ISSUE TITLE
Conflict with WPmandrill Plugin 

### ISSUE THREAD

**Issue by Optimized-Marketing** [Yoast/google-analytics-for-wordpress#287]
Once I upgraded to v5.2.8 WP no longer sent emails through Mandrill. It would only send them through the web host server. Which is a very unreliable. 

It works correctly on v5.2.7

**Comment by Willem-Siebe** [comment]
I have the same issue, as well as others: https://wordpress.org/support/topic/only-working-for-some-emails?replies=9#post-6447413, https://wordpress.org/support/topic/google-analytics-for-wp-and-mandrill-wp-plugin?replies=3#post-6447411.

**Comment by jchristopher** [comment]
I also experienced this issue. It's strange though because WooCommerce-generated emails were making it to Mandrill, but not Gravity Forms or my own calls to `wp_mail()`. I'm not sure if that helps track it down, but I recall this being an issue in a *fairly* recent release as well which might help get it resolved permanently.

**Comment by jarichypma** [comment]
After digging around some time I found out what the problem is.

Before sending an email, mandrill checks `if( function_exists('wp_mail') )`. This usually isn't the case, but since the release of google-analytics-for-wordpress version 5.2.8 somehow wp_mail() get's called when viewing a page. When submitting a form and sending notifications this leads mandrill to set `self::$conflict = true;` and send mail through WordPress' built-in mail-function using php-mail instead of allowing Mandrill to take over the mail-sending part.

It doesn't seem to happen everywhere, because resending notifications in gravity-forms does use mandrill. Disabling the analytics-pluging solves the problem, but this of course isn't a real solution.

I tried a quick search on the analytics-code to find some line calling the wp-mail function, but I couldn't find anything. I hope this helps the Yoast-team to tackle this issue.

**Comment by CarolineGeven** [comment]
Seems like regression from #53. Thanks for notifying us.

**Comment by jarichypma** [comment]
Hi Caroline,

Thank you for releasing this beta-version. I just installed 5.3-beta and tested this specific issue, this solves the problem with the mail-conflict. Mandrill again works like it's supposed to.

A big thank you to the Yoast-team for the quick response in solving this issue.

Regards,

Jarich

**Comment by CarolineGeven** [comment]
Thanks for letting us know! :)

**Comment by HARVS1789UK** [comment]
@CarolineGeven do you know when this fix you have released in a beta release is going to to be merged into a production release? I currently have a site which can either:

- Send WooCommerce E-mails to the site owner and customers using Mandrill
OR
- Have the Yoast GA for WordPress plugin enabled

Not both! I have tried to upgrade Yoast GA for WordPress to the most recent stable release (v5.3.2) in the hope that this bug has been patched but that stopped the admin pages under /wp-admin/ from working all together (I was just served blank pages) so I have reverted to v5.2.8

Can you advise how to resolve this and/or when the beta fixes wil be release in a stable production version?

Kind regards,

Joe

**Comment by Willem-Siebe** [comment]
@HARVS1789UK When 5.3 came out I updated the plugin and never had problems again with Mandrill, so solution should already be implemented in the plugin :-).

**Comment by HARVS1789UK** [comment]
Hi @Willem-Siebe thanks for the info. I tried to update to version 5.3 but it broke my live site so I reverted the upgrade. I didn't actually spend anytime attempting to work out why yet, so I may be able to upgrade. 

For now the client has informed me that they have purchased the premium version of the Yoast plugin anyway, so I am going to replace the free version with premium and see if it still conflicts. Ill note the results here.
